### ISSUE TITLE
Törékeny tesztek

### ISSUE THREAD

**Issue by vadalf** [Teaching-projects/SOE-SZTA-2021-Tuti-a-moodle#11]
Referencia: https://github.com/Teaching-projects/SOE-SZTA-2021-Tuti-a-moodle/pull/9#pullrequestreview-616917387

**Comment by vadalf** [comment]
@itsmehali @tmRobi Ezt oldjátok meg a [`gradle`](https://github.com/Teaching-projects/SOE-SZTA-2021-Tuti-a-moodle/tree/gradle) ágon, amíg zöld nem lesz a pipa. Idáig amúgy le se futottak azok a tesztek, amik miatt most piros a CI.

**Comment by Keelorath** [comment]
Na majd ránézek én is.
