### ISSUE TITLE
F4/2 - szintlepes

### ISSUE THREAD

**Issue by vadalf** [Teaching-projects/SOE-SZTA-2021-Tuti-a-moodle#18]
Legyen egy olyan osztaly, ami hasonloan mukodik, mint a sima Unit-unk, de valahany bevitt sebzesenkent szintet lep. minden szintlepesnel valamennyivel megno a ho, damage, es valamennyivel beszorzodik a cooldown. Szintlepeskor a hp felmegy a maximumra. A json file-ban ezeknek a parametereknek a kulcsai: `xp_per_level`, `dmg_increase_per_level`, `hp_increase_per_level`, valamint `cooldown_multiplier_per_level`. Az utolso float, a tobbi int. brach: `lvlup`. (a sima osztaly felel meg majd a kintlevo szornyeknek, ez az uj meg a jatekosnak, akit iranyitunk.)

**Comment by Keelorath** [comment]
@hegyhati azt válaszolta, hogy a sebzés értékével növekedjen az xp.
