### ISSUE TITLE
F4/3 - alap gui

### ISSUE THREAD

**Issue by vadalf** [Teaching-projects/SOE-SZTA-2021-Tuti-a-moodle#19]
Keszuljon egy nagyon alapszintu GUI kivalasztott technologiaval (nem kotelezo a Swing), melyben a kovetkezot lehet megtenni: bal es jobb oldalra be lehet tolteni 1-1 json file-bol 1-1 unit-ot, es ha ez megvan, akkor lent egy button, ami egymasnak ugrasztja eoket, az eredmenyt pedig valami felugro abakszerusegben mutassa meg. Branch: `gui`

**Comment by tmRobi** [comment]
@vadalf, szerintem megvannak a kritériumok.
